version: '3.3'

services:
  mongodb:
    container_name: mongo-db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://localhost:27017/taste-table
    volumes:
      - ./pgdata:/var/lib/postgresql/PG_DATABASE
    ports:
      - ${PG_LOCAL_PORT}:${PG_PORT}
  app:
    container_name: taste_table-docker
    build: 
      context: ./
    depends_on:
      - mongodb
    restart: unless-stopped
    ports:
      - ${API_LOCAL_PORT}:${API_PORT}
    environment:
      - API_PORT=${API_PORT}
      - API_LOCAL_PORT=${API_LOCAL_PORT}
      - PG_CONNECTION=${PG_CONNECTION}
      - PG_USERNAME=${PG_USERNAME}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_PORT=${PG_PORT}
      - PG_LOCAL_PORT=${PG_LOCAL_PORT}
      - PG_DATABASE=${PG_DATABASE}
      - PG_HOST=postgres